apiVersion: v1
kind: ConfigMap
metadata:
  name: agentor-config
data:
  config.json: |
    {
      "server": {
        "host": "0.0.0.0",
        "port": 8000,
        "workers": 4,
        "timeout": 300
      },
      "logging": {
        "level": "INFO",
        "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      },
      "metrics": {
        "enabled": true,
        "endpoint": "/metrics"
      },
      "circuit_breaker": {
        "failure_threshold": 5,
        "recovery_timeout": 30,
        "half_open_max_calls": 3
      },
      "retry": {
        "max_retries": 3,
        "base_delay": 1.0,
        "max_delay": 30.0
      },
      "timeout": {
        "default": 10.0,
        "max": 60.0
      },
      "bulkhead": {
        "max_concurrent": 20,
        "max_queue_size": 50
      },
      "cache": {
        "enabled": true,
        "ttl": 3600
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agentor-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
